# -*- mode: just -*-

export_flags := "--no-hashes --no-emit-project --format=requirements-txt"
audit_flags := "--desc --strict --progress-spinner=off"

# Test project
test:
    uv run pytest

# Check formatting with blue style
fmt:
    uv run ruff check --fix
    uv run ruff format

# Audit project dependencies
audit:
    uv tree
    # uv export {{export_flags}} > requirements.txt
    # uvx pip-audit {{audit_flags}} -r requirements.txt
    # Alternatively:
    uv tree
    uv pip compile pyproject.toml -o requirements.txt
    uvx pip-audit {{audit_flags}} -r requirements.txt --fix

# Benchmark performance
# bench:
#     TODO
